services:
  prometheus:
    image: prom/prometheus:latest
    # ports:
    #   - "9090:9090"
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - ./config:/config:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/config/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    # ports:
      # - "3000:3000"
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro

  node_exporter:
    image: prom/node-exporter:latest
    # ports:
    #   - "9100:9100"
    pid: host
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: google/cadvisor:latest
    # ports:
    #   - "8080:8080"
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: 
      - -logtostderr
      - -docker_only


volumes:
  prometheus_data:
  grafana_data:
