services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    # ports:
    #   - "9090:9090"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ./config:/config:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/config/prometheus.yml"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    # ports:
      # - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    # ports:
    #   - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    deploy:
      mode: global
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    # ports:
    #   - "8080:8080"
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg


volumes:
  prometheus_data:
  grafana_data:
